parameters:
  - name: juceVersions
    type: object

steps:
  - script: cmake --version
    displayName: CMake version

  - ${{ each juceVersion in parameters.juceVersions }}:
    - script: >
        git clone --branch=${{ juceVersion }} --depth=1 --single-branch
        -- https://github.com/juce-framework/JUCE.git ci/tmp/JUCE-${{ juceVersion }}
      displayName: Clone JUCE ${{ juceVersion }}

  - script: mkdir Debug_build
    displayName: mkdir Debug_build
  - script: mkdir Release_build
    displayName: mkdir Release_build

  - ${{ each juceVersion in parameters.juceVersions }}:
    - script: >
        cmake .. -G "$(cmakeGenerator)" -DCMAKE_BUILD_TYPE=Debug
        -DJUCE_ROOT="$(Build.SourcesDirectory)/ci/tmp/JUCE-${{ juceVersion }}"
      workingDirectory: Debug_build
      displayName: Configure FRUT with JUCE ${{ juceVersion }} (Debug)
    - script: cmake --build . --parallel
      workingDirectory: Debug_build
      displayName: Build FRUT with JUCE ${{ juceVersion }} (Debug)
    - script: >
        cmake .. -G "$(cmakeGenerator)" -DCMAKE_BUILD_TYPE=Release
        -DJUCE_ROOT="$(Build.SourcesDirectory)/ci/tmp/JUCE-${{ juceVersion }}"
      workingDirectory: Release_build
      displayName: Configure FRUT with JUCE ${{ juceVersion }} (Release)

  - script: >
      cmake .. -G "$(cmakeGenerator)"
      -DCMAKE_INSTALL_PREFIX="$(Build.SourcesDirectory)/prefix"
    workingDirectory: Release_build
    displayName: Configure FRUT for installation in ./prefix
  - script: cmake --build . --target install --parallel
    workingDirectory: Release_build
    displayName: Build and install FRUT in ./prefix

  - script: >
      cmake -DJucer2CMake_EXE="prefix/FRUT/bin/Jucer2CMake"
      -P Jucer2CMake/tests/apply-Jucer2CMake-juce6-to-test-jucers.cmake
    displayName: Re-generate CMakeLists.txt files for Jucer2CMake test projects
  - script: >
      cmake -DJucer2CMake_EXE="prefix/FRUT/bin/Jucer2CMake"
      -P ci/apply-Jucer2CMake-reprojucer-to-test-jucers.cmake
    displayName: Re-generate CMakeLists.txt files for test projects
  - ${{ each juceVersion in parameters.juceVersions }}:
    - script: >
        cmake -DJUCE_VERSION="${{ juceVersion }}"
        -DJucer2CMake_EXE="prefix/FRUT/bin/Jucer2CMake"
        -P ci/apply-Jucer2CMake-reprojucer-to-JUCE-jucers.cmake
      displayName: Re-generate CMakeLists.txt files for JUCE ${{ juceVersion }}
  - script: git diff --exit-code
    displayName: Check that generated CMakeLists.txt files are up-to-date

  - script: mkdir ci/AllJuceProjects/Debug_build
    displayName: mkdir ci/AllJuceProjects/Debug_build
  - script: mkdir ci/AllJuceProjects/Release_build
    displayName: mkdir ci/AllJuceProjects/Release_build

  - ${{ each juceVersion in parameters.juceVersions }}:
    - script: >
        cmake .. -G "$(cmakeGenerator)" -DCMAKE_BUILD_TYPE=Debug
        -DJUCE_VERSION="${{ juceVersion }}"
        -DJUCER_AAX_SDK_FOLDER="$(Build.SourcesDirectory)/ci/fake-SDKs/AAX"
        -DJUCER_VST3_SDK_FOLDER="$(Build.SourcesDirectory)/ci/fake-SDKs/VST3"
        -DJUCER_VST_SDK_FOLDER="$(Build.SourcesDirectory)/ci/fake-SDKs/VST"
      workingDirectory: ci/AllJuceProjects/Debug_build
      displayName: Configure all JUCE ${{ juceVersion }} projects (Debug)
    - script: >
        cmake .. -G "$(cmakeGenerator)" -DCMAKE_BUILD_TYPE=Release
        -DJUCE_VERSION="${{ juceVersion }}"
        -DJUCER_AAX_SDK_FOLDER="$(Build.SourcesDirectory)/ci/fake-SDKs/AAX"
        -DJUCER_VST3_SDK_FOLDER="$(Build.SourcesDirectory)/ci/fake-SDKs/VST3"
        -DJUCER_VST_SDK_FOLDER="$(Build.SourcesDirectory)/ci/fake-SDKs/VST"
      workingDirectory: ci/AllJuceProjects/Release_build
      displayName: Configure all JUCE ${{ juceVersion }} projects (Release)
